{% set name = "hypertab" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypertab-{{ version }}.tar.gz
  sha256: 2a428a0db93488ca4ff3572b076af6a8a1eb685375cbf6a4cffe49addc25965d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.10.1
    - python-dotenv >=0.21.0
    - scikit-learn >=0.24.2
    - setuptools >=59.8.0
    - pytorch
    - torchvision
    - tqdm >=4.64.0

test:
  imports:
    - hypertab
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/wwydmanski/hypertab
  summary: 'HyperTab: hypernetwork for small tabular datasets'
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - dillonroach
